### ISSUE TITLE
Fails in Google Colab

### ISSUE THREAD

**Issue by dschiller** [mostafaelaraby/wavegan-pytorch#9]
Fails with last Step

```bash
0% 1/250 [00:27<1:52:18, 27.06s/it, Loss_D WD=-0.02465313859283924, Loss_G=-0.41385307908058167, Val_G=-0.030089471489191055]Traceback (most recent call last):
  File "train.py", line 223, in <module>
    wave_gan.train()
  File "train.py", line 199, in train
    save_samples(fake, iter_indx)
  File "/content/wavegan-pytorch/utils.py", line 172, in save_samples
    librosa.output.write_wav(output_path, sample, sampling_rate)
AttributeError: module 'librosa' has no attribute 'output'
  0% 1/250 [00:28<1:57:56, 28.42s/it, Loss_D WD=-0.02465313859283924, Loss_G=-0.41385307908058167, Val_G=-0.030089471489191055]
```

**Comment by mostafaelaraby** [comment]
It seems the latest version of librosa has changed its Api, a safe plan would be to use version 0.6.3.
